# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e2eae4fcb9d4be9246b5619e40a4504ba958f7b26fb7eacc3fa4b95dfe71de63d4c094d969d61991c916944d1c169007a85710fbadc0676b4e3bf08e44bff69

test:
  secret_key_base: 88b11fbdaca639cc9ce9c918851296c873ebe604ddda903c1106cc3cb2465697cfb214350a946dafb90537ee24cf1af5c0d7a65d2dad895abf6336443e66e593

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
